state:
  is_dev: true
  # config_path: config.dev.yaml
  config_path: false
  check_db: true
server:
  # 根路由代理
  server_root_path: ""
  host: 0.0.0.0
  port: 2001
# 网络代理配置
# proxy:
#   type: http
#   host: 127.0.0.1
#   port: 18081
# 目录配置
dir:
  # 基础根目录
  base: temp_source

  # 子目录定义（按功能划分）
  base_child:
    source:     source      # 源代码/原始文件
    upload:   upload    # 用户上传文件(默认目录)
    log:        log         # 日志文件
    sys_out:    sys_out     # 系统输出（如运行结果、导出文件）
    temp:       temp        # 临时文件(解压缩之类)
    db:         db          # 数据库文件（如 SQLite、缓存等）
    test:       test        # 测试相关资源
    model:      model       # 模型文件
    lib_third:  lib_third   # 第三方库文件
  public: public
  
# 单独上传文件系统设置
file_system_upload:
  # 上传文件目录 local默认走 本地目录 dir.base配置的upload目录
  storage_type: local
  # 上传文件大小限制
  size: 1024 * 1024 * 10 # 10MB
  # 文件类型限制
  no_types:
    - "application/zip"
    - "application/pdf"
  # 本地存储配置
  local: ''
    # 使用已有的 base_child upload 目录
  # S3/MinIO/rustfs 存储配置
  # s3:
  #   endpoint: "http://localhost:9000"
  #   access_key: "minioadmin"
  #   secret_key: "minioadmin"
  #   bucket_name: "bucket0"
  #   region: "us-east-1"                # MinIO 通常可设为任意值，如 us-east-1
  #   secure: false  

# 中间件配置
middleware:
  cors: true
  gzip: true
####################### 数据库配置
db_rel:
  type: postgres
  database: server_example
  host: localhost
  port: 5432
  user: postgres
  password: '123456'
# db_rel:
#   type: sqlite
#   database: temp_source\db\data.db
# db_cache:
#   type: redis
#   db: 0
#   host: localhost
#   port: 6379
#   password: ''
#   database: temp_source\db\redis.db # 缓存持久化地址
db_cache:
  type: fakeredis
  database: temp_source\db\fakeredis.db
db_vector:
  type: lancedb
  database: temp_source\db\lancedb.db
db_graph:
  type: graph_local
  database: temp_source\db\graph_local.db
# db_graph:
#   type: neo4j
#   host: 127.0.0.1
#   port: 7687
#   user: neo4j
#   password: 123456
#   database: neo4j
####################### auth 配置
token:
  secret_key: qwer1234
  algorithm: HS256
  expire_minutes: 30000
  refresh_expire_days: 20
# 邮箱配置
email:
  smtp_server: todo
  smtp_port: 465
  sender_email: todo
  sender_password: todo # 授权码
  sender_name: todo # 发件人 可以不写
